dirw, "List of files in a wide format", "ls -la"
net, "Check google connection", "ping -c 4 google.com"
sys, "Show system processes", "ps aux"
temp, "Quick jump to Work folder", "/mnt/d/temp"
bin, "Quick jump to Documents", "/bin"
monkey, "Quick jump to Monkey Island games", "/mnt/d/MonkeyIsland"
epic, "Quick jump to Epic games", "/mnt/d/Epic Games"
fortnite, "Quick jumo to Fortnite game", "/mnt/d/Epic Games/Fortnite"
